"""
Validation, round-tripping, and a scenario shaped nothing like the supplied ones.

The second half of this file is the insurance against the thing most likely to cost
points on the day: the judges upload their own file. `tests/fixtures/judge_fixture.json`
is generated by `scripts/make_fixture.py` and breaks every assumption the four
supplied scenarios would let a reader make — four planes, ten satellites each,
batches cutting across planes, two gateways, a gateway outage, a different altitude
and grid. If anything in the package quietly assumes 3 × 16 with one Murmansk
station, these tests are where it shows up.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from cosmo_net.analysis.criticality import rank_satellites
from cosmo_net.analysis.optimise import sweep_spacing
from cosmo_net.analysis.simulate import simulate, snapshot_at
from cosmo_net.config import SCENARIOS_DIR
from cosmo_net.scenario.io import dump_scenario, load_scenario, loads_scenario
from cosmo_net.scenario.schema import ScenarioInvalid, parse_scenario

FIXTURE = Path(__file__).parent / "fixtures" / "judge_fixture.json"


@pytest.fixture(scope="module")
def raw() -> dict:
    return json.loads((SCENARIOS_DIR / "01_full_constellation.json").read_text(encoding="utf-8"))


def problems(data: dict) -> dict[str, str]:
    """Field path → error code, for whatever is wrong with `data`."""

    with pytest.raises(ScenarioInvalid) as caught:
        parse_scenario(data)
    return {error.field: error.code for error in caught.value.errors}


def test_every_supplied_scenario_round_trips():
    """An edited variant has to be exportable and loadable again, so the trip must be exact."""

    for path in sorted(SCENARIOS_DIR.glob("*.json")):
        original = json.loads(path.read_text(encoding="utf-8"))
        assert dump_scenario(load_scenario(path)) == original, path.name


def test_malformed_json_is_reported_with_a_position():
    with pytest.raises(ScenarioInvalid) as caught:
        loads_scenario('{"schema_version": "cosmo-A-1.0",,}')
    error = caught.value.errors[0]
    assert error.code == "malformed_json"
    assert "строка" in error.message


def test_another_schema_version_is_refused(raw):
    data = copy.deepcopy(raw)
    data["schema_version"] = "cosmo-A-2.0"
    assert problems(data) == {"schema_version": "unsupported_schema"}


def test_a_satellite_pointing_at_no_plane(raw):
    data = copy.deepcopy(raw)
    data["design"]["satellites"][12]["plane_id"] = "P9"
    assert problems(data) == {"design.satellites[12].plane_id": "unknown_plane"}


def test_duplicate_satellite_identifiers(raw):
    data = copy.deepcopy(raw)
    data["design"]["satellites"][5]["id"] = data["design"]["satellites"][4]["id"]
    assert problems(data) == {"design.satellites[5].id": "duplicate_id"}


def test_a_ground_site_may_not_take_a_satellite_identifier(raw):
    data = copy.deepcopy(raw)
    data["ground_sites"][1]["id"] = "S01"
    assert problems(data) == {"ground_sites[1].id": "id_collides_with_satellite"}


def test_horizon_must_be_whole_steps(raw):
    data = copy.deepcopy(raw)
    data["environment"]["horizon_s"] = 86_401
    assert problems(data) == {"environment.horizon_s": "horizon_not_multiple_of_step"}


def test_a_float_time_grid_is_refused(raw):
    """
    The reference module checks `isinstance(..., int)`, so 86400.0 fails there.

    Accepting it here would produce a file that works in this service and is rejected
    by the organisers' own tool, which is worse than refusing it.
    """

    data = copy.deepcopy(raw)
    data["environment"]["step_s"] = 120.0
    assert problems(data) == {"environment.step_s": "int_type"}


def test_an_outage_past_the_horizon(raw):
    data = copy.deepcopy(raw)
    data["failures"] = [{"satellite_id": "S01", "start_s": 80_000, "end_s": 90_000}]
    assert problems(data) == {"failures[0].end_s": "interval_past_horizon"}


def test_an_outage_with_no_length(raw):
    data = copy.deepcopy(raw)
    data["failures"] = [{"satellite_id": "S01", "start_s": 600, "end_s": 600}]
    assert problems(data) == {"failures[0].end_s": "interval_not_positive"}


def test_an_outage_naming_no_satellite(raw):
    data = copy.deepcopy(raw)
    data["failures"] = [{"satellite_id": "S99", "start_s": 0, "end_s": 600}]
    assert problems(data) == {"failures[0].satellite_id": "unknown_satellite"}


def test_a_gateway_outage_naming_a_client(raw):
    data = copy.deepcopy(raw)
    data["gateway_outages"] = [{"gateway_id": "C65", "start_s": 0, "end_s": 600}]
    assert problems(data) == {"gateway_outages[0].gateway_id": "unknown_gateway"}


def test_a_scenario_with_no_gateway(raw):
    data = copy.deepcopy(raw)
    data["ground_sites"] = [s for s in data["ground_sites"] if s["role"] != "gateway"]
    assert problems(data) == {"ground_sites": "no_gateway"}


def test_every_problem_is_reported_at_once(raw):
    """
    One upload, one list of everything to fix.

    The reference module raises on the first problem, which means fixing a file by
    trial and error. The case asks the service to say which field or object is wrong,
    and a user with three mistakes should learn about three of them.
    """

    data = copy.deepcopy(raw)
    data["design"]["satellites"][0]["plane_id"] = "P9"
    data["design"]["satellites"][3]["id"] = data["design"]["satellites"][2]["id"]
    data["failures"] = [{"satellite_id": "S99", "start_s": 0, "end_s": 600}]

    found = problems(data)
    assert set(found) == {
        "design.satellites[0].plane_id",
        "design.satellites[3].id",
        "failures[0].satellite_id",
    }


def test_unknown_fields_survive_a_round_trip(raw):
    """A judge's file carrying an annotation this service ignores comes back carrying it."""

    data = copy.deepcopy(raw)
    data["meta"]["author"] = "jury"
    data["environment"]["notes"] = "as supplied"
    assert dump_scenario(parse_scenario(data)) == data


# --- a scenario of a different shape entirely ------------------------------------


@pytest.fixture(scope="module")
def judge_fixture():
    if not FIXTURE.exists():
        pytest.skip("run: uv run python scripts/make_fixture.py")
    return load_scenario(FIXTURE)


def test_the_fixture_is_not_shaped_like_the_supplied_scenarios(judge_fixture):
    assert len(judge_fixture.design.planes) == 4
    assert len(judge_fixture.design.satellites) == 40
    assert len(judge_fixture.gateways) == 2
    assert judge_fixture.gateway_outages
    assert judge_fixture.environment.step_s == 60

    # Launch batches cut across planes rather than coinciding with them, which is
    # the assumption the supplied files invite and this one refuses.
    per_plane = {plane.id: set() for plane in judge_fixture.design.planes}
    for satellite in judge_fixture.design.satellites:
        per_plane[satellite.plane_id].add(satellite.launch_batch)
    assert all(len(batches) > 1 for batches in per_plane.values())


def test_the_whole_pipeline_runs_on_the_fixture(judge_fixture):
    result = simulate(judge_fixture)
    assert len(result.times_s) == 720
    assert set(result.metrics) == {"TERM-1", "TERM-2"}
    for metrics in result.metrics.values():
        assert 0.0 < metrics.availability_share <= 1.0


def test_both_gateways_are_used(judge_fixture):
    """With two destinations the search has a choice, and it takes both."""

    result = simulate(judge_fixture)
    used = {route.gateway_id for routes in result.routes.values() for route in routes if route}
    assert used == {"GW-WEST", "GW-EAST"}


def test_the_gateway_outage_changes_the_answer(judge_fixture):
    """The branch no supplied scenario exercises: remove it and availability rises."""

    without = judge_fixture.model_copy(deep=True)
    without.gateway_outages = []
    assert simulate(without).worst_availability > simulate(judge_fixture).worst_availability


def test_studies_run_on_the_fixture(judge_fixture):
    """
    Criticality and the sweep must not assume three planes or sixteen craft each.

    39 knockouts and not 40: SAT-127 is already out for the whole horizon in this
    fixture, and removing something that was never there measures nothing.
    """

    report = rank_satellites(judge_fixture)
    assert len(report.knockouts) == 39
    assert "SAT-127" not in {k.satellite_id for k in report.knockouts}

    sweep = sweep_spacing(judge_fixture)
    assert len(sweep.best.raan_deg) == 4
    assert sweep.best.worst_availability >= sweep.baseline.worst_availability


def test_a_snapshot_can_be_taken_at_any_moment(judge_fixture):
    snapshot = snapshot_at(judge_fixture, 9_000)
    assert len(snapshot.satellites) == 40
    assert all(-90 <= s["lat_deg"] <= 90 for s in snapshot.satellites)
    assert all(-180 <= s["lon_deg"] <= 180 for s in snapshot.satellites)
